name: 🤖 Auto remove label on closed issue
on:
    issues:
        types: [closed]

jobs:
    remove_label:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4.2.1
            - uses: taiga-family/ci/actions/auto/remove-label@v1.132.0
