name: ⚙️ Build

on:
    pull_request:
    push:
        branches: [main]

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4.2.2
            - uses: taiga-family/ci/actions/setup/node@v1.138.0
            - run: npm run build

concurrency:
    group: build-${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true
