name: ⚙️ Lint

on:
    pull_request:
    push:
        branches: [main]

jobs:
    lint:
        name: Lint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
            - uses: taiga-family/ci/actions/setup/node@a6230c2ffdf53253580ec058dd4faccdb01ac85a # v2.4.0
            - run: npm run prettier -- --check

concurrency:
    group: lint-${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true
