name: 🤖 PR is ready to merge
on:
  pull_request_review:
    types: [submitted]

jobs:
  label-when-approved:
    name: Label when approved
    runs-on: ubuntu-latest
    if: github.event.review.state == 'approved'
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: taiga-family/ci/actions/setup/variables@ad2e311a6700d8fc7efab79f8b8a2165888ff968 # v2.20.0
      - uses: taiga-family/ci/actions/auto/label-when-approved@ad2e311a6700d8fc7efab79f8b8a2165888ff968 # v2.20.0
        with:
          approvals: 1
          token: ${{ secrets.GITHUB_TOKEN }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
